export const GET_ALL_NEW_SOURCES_STUDENT_REQUEST =
  "GET_ALL_NEW_SOURCES_STUDENT_REQUEST";
export const GET_ALL_NEW_SOURCES_STUDENT_SUCCESS =
  "GET_ALL_NEW_SOURCES_STUDENT_SUCCESS";
export const GET_ALL_NEW_SOURCES_STUDENT_FAIL =
  "GET_ALL_NEW_SOURCES_STUDENT_FAIL";
export const GET_ALL_NEW_SOURCES_STUDENT_RESET =
  "GET_ALL_NEW_SOURCES_STUDENT_RESET";

export const GET_NEW_SOURCES_STUDENT_LIST_REQUEST = "GET_NEW_SOURCES_STUDENT_LIST_REQUEST";
export const GET_NEW_SOURCES_STUDENT_LIST_SUCCESS = "GET_NEW_SOURCES_STUDENT_LIST_SUCCESS";
export const GET_NEW_SOURCES_STUDENT_LIST_FAIL = "GET_NEW_SOURCES_STUDENT_LIST_FAIL";
export const GET_NEW_SOURCES_STUDENT_LIST_RESET = "GET_NEW_SOURCES_STUDENT_LIST_RESET";

export const DOWNLOAD_NEW_SOURCES_REQUEST = "DOWNLOAD_NEW_SOURCES_REQUEST";
export const DOWNLOAD_NEW_SOURCES_SUCCESS = "DOWNLOAD_NEW_SOURCES_SUCCESS";
export const DOWNLOAD_NEW_SOURCES_FAIL = "DOWNLOAD_NEW_SOURCES_FAIL";
export const DOWNLOAD_NEW_SOURCES_RESET = "DOWNLOAD_NEW_SOURCES_RESET";