export const GET_ALL_FAMILYMEMBER_REQUEST = 'GET_ALL_FAMILYMEMBER_REQUEST';
export const GET_ALL_FAMILYMEMBER_SUCCESS = 'GET_ALL_FAMILYMEMBER_SUCCESS';
export const GET_ALL_FAMILYMEMBER_FAIL = 'GET_ALL_FAMILYMEMBER_FAIL';
export const GET_ALL_FAMILYMEMBER_RESET = 'GET_ALL_FAMILYMEMBER_RESET';

export const UPDATE_SINGLE_FAMILYMEMBER_REQUEST = 'UPDATE_SINGLE_FAMILYMEMBER_REQUEST';
export const UPDATE_SINGLE_FAMILYMEMBER_SUCCESS = 'UPDATE_SINGLE_FAMILYMEMBER_SUCCESS';
export const UPDATE_SINGLE_FAMILYMEMBER_FAIL = 'UPDATE_SINGLE_FAMILYMEMBER_FAIL';
export const UPDATE_SINGLE_FAMILYMEMBER_RESET = 'UPDATE_SINGLE_FAMILYMEMBER_RESET';

export const GET_SINGLE_FAMILYMEMBER_REQUEST = "GET_SINGLE_FAMILYMEMBER_REQUEST";
export const GET_SINGLE_FAMILYMEMBER_SUCCESS = "GET_SINGLE_FAMILYMEMBER_SUCCESS";
export const GET_SINGLE_FAMILYMEMBER_FAIL = "GET_SINGLE_FAMILYMEMBER_FAIL";
export const GET_SINGLE_FAMILYMEMBER_RESET = "GET_SINGLE_FAMILYMEMBER_RESET";

export const GET_ALL_FAMILYMEMBER_CREATE_REQUEST = 'GET_ALL_FAMILYMEMBER_CREATE_REQUEST';
export const GET_ALL_FAMILYMEMBER_CREATE_SUCCESS = 'GET_ALL_FAMILYMEMBER_CREATE_SUCCESS';
export const GET_ALL_FAMILYMEMBER_CREATE_FAIL = 'GET_ALL_FAMILYMEMBER_CREATE_FAIL';
export const GET_ALL_FAMILYMEMBER_CREATE_RESET = 'GET_ALL_FAMILYMEMBER_CREATE_RESET';

export const FAMILYMEMBER_CREATE_REQUEST = 'FAMILYMEMBER_CREATE_REQUEST';
export const FAMILYMEMBER_CREATE_SUCCESS = 'FAMILYMEMBER_CREATE_SUCCESS';
export const FAMILYMEMBER_CREATE_FAIL = 'FAMILYMEMBER_CREATE_FAIL';
export const FAMILYMEMBER_CREATE_RESET = 'FAMILYMEMBER_CREATE_RESET';