export const STUDENT_GET_ALL_ACADEMIC_GRADING_REQUEST =
  "STUDENT_GET_ALL_ACADEMIC_GRADING_REQUEST";
export const STUDENT_GET_ALL_ACADEMIC_GRADING_SUCCESS =
  "GET_ALL_ACADEMID_GRADING_SUCCESS";
export const STUDENT_GET_ALL_ACADEMIC_GRADING_FAIL =
  "STUDENT_GET_ALL_ACADEMIC_GRADING_FAIL";
export const STUDENT_GET_ALL_ACADEMIC_GRADING_RESET =
  "STUDENT_GET_ALL_ACADEMIC_GRADING_RESET";

export const STUDENT_GET_SINGLE_ACADEMIC_GRADING_REQUEST =
  "STUDENT_GET_SINGLE_ACADEMIC_GRADING_REQUEST";
export const STUDENT_GET_SINGLE_ACADEMIC_GRADING_SUCCESS =
  "STUDENT_GET_SINGLE_ACADEMIC_GRADING_SUCCESS";
export const STUDENT_GET_SINGLE_ACADEMIC_GRADING_FAIL =
  "STUDENT_GET_SINGLE_ACADEMIC_GRADING_FAIL";
export const STUDENT_GET_SINGLE_ACADEMIC_GRADING_RESET =
  "STUDENT_GET_SINGLE_ACADEMIC_GRADING_RESET";

export const STUDENT_CREATE_ACADEMIC_GRADING_REQUEST =
  "STUDENT_CREATE_ACADEMIC_GRADING_REQUEST";
export const STUDENT_CREATE_ACADEMIC_GRADING_SUCCESS =
  "STUDENT_CREATE_ACADEMIC_GRADING_SUCCESS";
export const STUDENT_CREATE_ACADEMIC_GRADING_FAIL =
  "STUDENT_CREATE_ACADEMIC_GRADING_FAIL";
export const STUDENT_CREATE_ACADEMIC_GRADING_RESET =
  "STUDENT_CREATE_ACADEMIC_GRADING_RESET";

export const STUDENT_GET_SINGLE_ACADEMIC_GRADING_EDIT_REQUEST =
  "STUDENT_GET_SINGLE_ACADEMIC_GRADING_EDIT_REQUEST";
export const STUDENT_GET_SINGLE_ACADEMIC_GRADING_EDIT_SUCCESS =
  "STUDENT_GET_SINGLE_ACADEMIC_GRADING_EDIT_SUCCESS";
export const STUDENT_GET_SINGLE_ACADEMIC_GRADING_EDIT_FAIL =
  "STUDENT_GET_SINGLE_ACADEMIC_GRADING_EDIT_FAIL";
export const STUDENT_GET_SINGLE_ACADEMIC_GRADING_EDIT_RESET =
  "STUDENT_GET_SINGLE_ACADEMIC_GRADING_EDIT_RESET";

export const STUDENT_UPDATE_SINGLE_ACADEMIC_GRADING_REQUEST =
  "STUDENT_UPDATE_SINGLE_ACADEMIC_GRADING_REQUEST";
export const STUDENT_UPDATE_SINGLE_ACADEMIC_GRADING_SUCCESS =
  "STUDENT_UPDATE_SINGLE_ACADEMIC_GRADING_SUCCESS";
export const STUDENT_UPDATE_SINGLE_ACADEMIC_GRADING_FAIL =
  "STUDENT_UPDATE_SINGLE_ACADEMIC_GRADING_FAIL";
export const UPDATE_SINGLE_ACADEMIC_GADING_RESET =
  "UPDATE_SINGLE_ACADEMIC_GADING_RESET";
