export const GET_ALL_HOLIDAY_REQUEST = "GET_ALL_HOLIDAY_REQUEST";
export const GET_ALL_HOLIDAY_SUCCESS = "GET_ALL_HOLIDAY_SUCCESS";
export const GET_ALL_HOLIDAY_FAIL = "GET_ALL_HOLIDAY_FAIL";
export const GET_ALL_HOLIDAY_RESET = "GET_ALL_HOLIDAY_RESET";

export const HOLIDAY_CREATE_REQUEST = "HOLIDAY_CREATE_REQUEST";
export const HOLIDAY_CREATE_SUCCESS = "HOLIDAY_CREATE_SUCCESS";
export const HOLIDAY_CREATE_FAIL = "HOLIDAY_CREATE_FAIL";
export const HOLIDAY_CREATE_RESET = "HOLIDAY_CREATE_RESET";

export const GET_SINGLE_HOLIDAY_REQUEST = "GET_SINGLE_HOLIDAY_REQUEST";
export const GET_SINGLE_HOLIDAY_SUCCESS = "GET_SINGLE_HOLIDAY_SUCCESS";
export const GET_SINGLE_HOLIDAY_FAIL = "GET_SINGLE_HOLIDAY_FAIL";
export const GET_SINGLE_HOLIDAY_RESET = "GET_SINGLE_HOLIDAY_RESET";

export const UPDATE_SINGLE_HOLIDAY_REQUEST = "UPDATE_SINGLE_HOLIDAY_REQUEST";
export const UPDATE_SINGLE_HOLIDAY_SUCCESS = "UPDATE_SINGLE_HOLIDAY_SUCCESS";
export const UPDATE_SINGLE_HOLIDAY_FAIL = "UPDATE_SINGLE_HOLIDAY_FAIL";
export const UPDATE_SINGLE_HOLIDAY_RESET = "UPDATE_SINGLE_HOLIDAY_RESET";
