export const GET_ALL_CLASS_SCHEDULE_REQUEST = "GET_ALL_CLASS_SCHEDULE_REQUEST";
export const GET_ALL_CLASS_SCHEDULE_SUCCESS = "GET_ALL_CLASS_SCHEDULE_SUCCESS";
export const GET_ALL_CLASS_SCHEDULE_FAIL = "GET_ALL_CLASS_SCHEDULE_FAIL";
export const GET_ALL_CLASS_SCHEDULE_RESET = "GET_ALL_CLASS_SCHEDULE_RESET";
