export const subject = [
  {
    id: 1,
    name: "Science",
    credit: "(Sci Cr: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/6mPDc4f/Science-Quotes.jpg",
  },
  {
    id: 2,
    name: "English",
    credit: "(Eng Cr: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/sypZmq4/english.jpg",
  },
  {
    id: 3,
    name: "Nepali",
    credit: "(Nep Cr: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/6mPDc4f/Science-Quotes.jpg",
  },
  {
    id: 4,
    name: "Socail Studies",
    credit: "(Ss Cr: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/5s20zQR/ss.jpg",
  },
  {
    id: 5,
    name: "Math",
    credit: "(Mth Cr: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/6mPDc4f/Science-Quotes.jpg",
  },
  {
    id: 6,
    name: "General Knowledge",
    credit: "(Gk Cr: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/Sw0XwNG/gk.jpg",
  },
  {
    id: 7,
    name: "Opt. Math",
    credit: "(Opt Cr: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/6mPDc4f/Science-Quotes.jpg",
  },
  {
    id: 8,
    name: "Computer science",
    credit: "(Cs Cr: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/ggPc7Lt/computer.jpg",
  },
];
