export const STUDENT_GET_ALL_LEAVE_REQUESTS_REQUEST =
  "STUDENT_GET_ALL_LEAVE_REQUESTS_REQUEST";
export const STUDENT_GET_ALL_LEAVE_REQUESTS_SUCCESS =
  "STUDENT_GET_ALL_LEAVE_REQUESTS_SUCCESS";
export const STUDENT_GET_ALL_LEAVE_REQUESTS_FAIL =
  "STUDENT_GET_ALL_LEAVE_REQUESTS_FAIL";
export const STUDENT_GET_ALL_LEAVE_REQUESTS_RESET =
  "STUDENT_GET_ALL_LEAVE_REQUESTS_RESET";

export const STUDENT_GET_LIST_LEAVE_REQUESTS_REQUEST =
  "STUDENT_GET_LIST_LEAVE_REQUESTS_REQUEST";
export const STUDENT_GET_LIST_LEAVE_REQUESTS_SUCCESS =
  "STUDENT_GET_LIST_LEAVE_REQUESTS_SUCCESS";
export const STUDENT_GET_LIST_LEAVE_REQUESTS_FAIL =
  "STUDENT_GET_LIST_LEAVE_REQUESTS_FAIL";
export const STUDENT_GET_LIST_LEAVE_REQUESTS_RESET =
  "STUDENT_GET_LIST_LEAVE_REQUESTS_RESET";

export const STUDENT_GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_REQUEST =
  "STUDENT_GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_REQUEST";
export const STUDENT_GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_SUCCESS =
  "STUDENT_GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_SUCCESS";
export const STUDENT_GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_FAIL =
  "STUDENT_GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_FAIL";
export const STUDENT_GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_RESET =
  "STUDENT_GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_RESET";

export const STUDENT_GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_REQUEST =
  "STUDENT_GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_REQUEST";
export const STUDENT_GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_SUCCESS =
  "STUDENT_GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_SUCCESS";
export const STUDENT_GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_FAIL =
  "STUDENT_GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_FAIL";
export const STUDENT_GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_RESET =
  "STUDENT_GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_RESET";

export const STUDENT_POST_LEAVE_REQUESTS_REQUEST =
  "STUDENT_POST_LEAVE_REQUESTS_REQUEST";
export const STUDENT_POST_LEAVE_REQUESTS_SUCCESS =
  "STUDENT_POST_LEAVE_REQUESTS_SUCCESS";
export const STUDENT_POST_LEAVE_REQUESTS_FAIL =
  "STUDENT_POST_LEAVE_REQUESTS_FAIL";
export const STUDENT_POST_LEAVE_REQUESTS_RESET =
  "STUDENT_POST_LEAVE_REQUESTS_RESET";

export const STUDENT_PUT_LEAVE_REQUESTS_REQUEST =
  "STUDENT_PUT_LEAVE_REQUESTS_REQUEST";
export const STUDENT_PUT_LEAVE_REQUESTS_SUCCESS =
  "STUDENT_PUT_LEAVE_REQUESTS_SUCCESS";
export const STUDENT_PUT_LEAVE_REQUESTS_FAIL =
  "STUDENT_PUT_LEAVE_REQUESTS_FAIL";
export const STUDENT_PUT_LEAVE_REQUESTS_RESET =
  "STUDENT_PUT_LEAVE_REQUESTS_RESET";

export const STUDENT_GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_REQUEST =
  "STUDENT_GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_REQUEST";
export const STUDENT_GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_SUCCESS =
  "STUDENT_GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_SUCCESS";
export const STUDENT_GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_FAIL =
  "STUDENT_GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_FAIL";
export const STUDENT_GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_RESET =
  "STUDENT_GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_RESET";

export const STUDENT_DELETE_LEAVE_REQUESTS_REQUEST =
  "STUDENT_DELETE_LEAVE_REQUESTS_REQUEST";
export const STUDENT_DELETE_LEAVE_REQUESTS_SUCCESS =
  "STUDENT_DELETE_LEAVE_REQUESTS_SUCCESS";
export const STUDENT_DELETE_LEAVE_REQUESTS_FAIL =
  "STUDENT_DELETE_LEAVE_REQUESTS_FAIL";
export const STUDENT_DELETE_LEAVE_REQUESTS_RESET =
  "STUDENT_DELETE_LEAVE_REQUESTS_RESET";

export const STUDENT_DOWNLOAD_DOC_LEAVE_REQUESTS_REQUEST =
  "STUDENT_DOWNLOAD_DOC_LEAVE_REQUESTS_REQUEST";
export const STUDENT_DOWNLOAD_DOC_LEAVE_REQUESTS_SUCCESS =
  "STUDENT_DOWNLOAD_DOC_LEAVE_REQUESTS_SUCCESS";
export const STUDENT_DOWNLOAD_DOC_LEAVE_REQUESTS_FAIL =
  "STUDENT_DOWNLOAD_DOC_LEAVE_REQUESTS_FAIL";
export const STUDENT_DOWNLOAD_DOC_LEAVE_REQUESTS_RESET =
  "STUDENT_DOWNLOAD_DOC_LEAVE_REQUESTS_RESET";
