export const GET_ALL_STUDENT_ATTENDANCE_REQUEST =
  "GET_ALL_STUDENT_ATTENDANCE_REQUEST";
export const GET_ALL_STUDENT_ATTENDANCE_SUCCESS =
  "GET_ALL_STUDENT_ATTENDANCE_SUCCESS";
export const GET_ALL_STUDENT_ATTENDANCE_FAIL =
  "GET_ALL_STUDENT_ATTENDANCE_FAIL";
export const GET_ALL_STUDENT_ATTENDANCE_RESET =
  "GET_ALL_STUDENT_ATTENDANCE_RESET";

  export const GET_ALL_OTHER_OPTIONS_FOR_STUDENT_REQUEST =
  "GET_ALL_OTHER_OPTIONS_FOR_STUDENT_REQUEST";
export const GET_ALL_OTHER_OPTIONS_FOR_STUDENT_SUCCESS =
  "GET_ALL_OTHER_OPTIONS_FOR_STUDENT_SUCCESS";
export const GET_ALL_OTHER_OPTIONS_FOR_STUDENT_FAIL =
  "GET_ALL_OTHER_OPTIONS_FOR_STUDENT_FAIL";
export const GET_ALL_OTHER_OPTIONS_FOR_STUDENT_RESET =
  "GET_ALL_OTHER_OPTIONS_FOR_STUDENT_RESET";

export const GET_ENGLISH_DATE_STUDENT_REQUEST = "GET_ENGLISH_DATE_STUDENT_REQUEST";
export const GET_ENGLISH_DATE_STUDENT_SUCCESS = "GET_ENGLISH_DATE_STUDENT_SUCCESS";
export const GET_ENGLISH_DATE_STUDENT_FAIL = "GET_ENGLISH_DATE_STUDENT_FAIL";
export const GET_ENGLISH_DATE_STUDENT_RESET = "GET_ENGLISH_DATE_STUDENT_RESET";

export const GET_LIST_STUDENT_ATTENDANCE_REQUEST =
  "GET_LIST_STUDENT_ATTENDANCE_REQUEST";
export const GET_LIST_STUDENT_ATTENDANCE_SUCCESS =
  "GET_LIST_STUDENT_ATTENDANCE_SUCCESS";
export const GET_LIST_STUDENT_ATTENDANCE_FAIL = "GET_LIST_STUDENT_ATTENDANCE_FAIL";
export const GET_LIST_STUDENT_ATTENDANCE_RESET = "GET_LIST_STUDENT_ATTENDANCE_RESET";

// export const GET_LIST_FOR_UPDATE_STUDENT_PRESENT_REQUEST =
//   "GET_LIST_FOR_UPDATE_STUDENT_PRESENT_REQUEST";
// export const GET_LIST_FOR_UPDATE_STUDENT_PRESENT_SUCCESS =
//   "GET_LIST_FOR_UPDATE_STUDENT_PRESENT_SUCCESS";
// export const GET_LIST_FOR_UPDATE_STUDENT_PRESENT_FAIL =
//   "GET_LIST_FOR_UPDATE_STUDENT_PRESENT_FAIL";
// export const GET_LIST_FOR_UPDATE_STUDENT_PRESENT_RESET =
//   "GET_LIST_FOR_UPDATE_STUDENT_PRESENT_RESET";

// export const GET_BULK_ATTENDANCE_STUDENT_REQUEST =
//   "GET_BULK_ATTENDANCE_STUDENT_REQUEST";
// export const GET_BULK_ATTENDANCE_STUDENT_SUCCESS =
//   "GET_BULK_ATTENDANCE_STUDENT_SUCCESS";
// export const GET_BULK_ATTENDANCE_STUDENT_FAIL =
//   "GET_BULK_ATTENDANCE_STUDENT_FAIL";
// export const GET_BULK_ATTENDANCE_STUDENT_RESET =
//   "GET_BULK_ATTENDANCE_STUDENT_RESET";

// export const POST_STUDENT_ATTENDANCE_REQUEST =
//   "POST_STUDENT_ATTENDANCE_REQUEST";
// export const POST_STUDENT_ATTENDANCE_SUCCESS =
//   "POST_STUDENT_ATTENDANCE_SUCCESS";
// export const POST_STUDENT_ATTENDANCE_FAIL = "POST_STUDENT_ATTENDANCE_FAIL";
// export const POST_STUDENT_ATTENDANCE_RESET =
//   "POST_STUDENT_ATTENDANCE_RESET";
