export const GET_ALL_UPLOADPHOTO_STUDENT_REQUEST = "GET_ALL_UPLOADPHOTO_STUDENT_REQUEST";
export const GET_ALL_UPLOADPHOTO_STUDENT_SUCCESS = "GET_ALL_UPLOADPHOTO_STUDENT_SUCCESS";
export const GET_ALL_UPLOADPHOTO_STUDENT_FAIL = "GET_ALL_UPLOADPHOTO_STUDENT_FAIL";
export const GET_ALL_UPLOADPHOTO_STUDENT_RESET = "GET_ALL_UPLOADPHOTO_STUDENT_RESET";

export const UPLOADPHOTO_STUDENT_REQUEST = "UPLOADPHOTO_STUDENT_REQUEST";
export const UPLOADPHOTO_STUDENT_SUCCESS = "UPLOADPHOTO_STUDENT_SUCCESS";
export const UPLOADPHOTO_STUDENT_FAIL = "UPLOADPHOTO_STUDENT_FAIL";
export const UPLOADPHOTO_STUDENT_RESET = "UPLOADPHOTO_STUDENT_RESET";
