export const GET_ALL_PERSONALINFORMATION_REQUEST =
  "GET_ALL_PERSONALINFORMATION_REQUEST";
export const GET_ALL_PERSONALINFORMATION_SUCCESS =
  "GET_ALL_PERSONALINFORMATION_SUCCESS";
export const GET_ALL_PERSONALINFORMATION_FAIL =
  "GET_ALL_PERSONALINFORMATION_FAIL";
export const GET_ALL_PERSONALINFORMATION_RESET =
  "GET_ALL_PERSONALINFORMATION_RESET";

export const GET_SINGLE_PERSONALINFORMATION_REQUEST =
  "GET_SINGLE_PERSONALINFORMATION_REQUEST";
export const GET_SINGLE_PERSONALINFORMATION_SUCCESS =
  "GET_SINGLE_PERSONALINFORMATION_SUCCESS";
export const GET_SINGLE_PERSONALINFORMATION_FAIL =
  "GET_SINGLE_PERSONALINFORMATION_FAIL";
export const GET_SINGLE_PERSONALINFORMATION_RESET =
  "GET_SINGLE_PERSONALINFORMATION_RESET";

export const UPDATE_SINGLE_PERSONALINFORMATION_REQUEST =
  "UPDATE_SINGLE_PERSONALINFORMATION_REQUEST";
export const UPDATE_SINGLE_PERSONALINFORMATION_SUCCESS =
  "UPDATE_SINGLE_PERSONALINFORMATION_SUCCESS";
export const UPDATE_SINGLE_PERSONALINFORMATION_FAIL =
  "UPDATE_SINGLE_PERSONALINFORMATION_FAIL";
export const UPDATE_SINGLE_PERSONALINFORMATION_RESET =
  "UPDATE_SINGLE_PERSONALINFORMATION_RESET";

export const GET_TEACHER_RESET_PASSWORD_REQUEST =
  "GET_TEACHER_RESET_PASSWORD_REQUEST";
export const GET_TEACHER_RESET_PASSWORD_SUCCESS =
  "GET_TEACHER_RESET_PASSWORD_SUCCESS";
export const GET_TEACHER_RESET_PASSWORD_FAIL =
  "GET_TEACHER_RESET_PASSWORD_FAIL";
export const GET_TEACHER_RESET_PASSWORD_RESET =
  "GET_TEACHER_RESET_PASSWORD_RESET";

export const POST_TEACHER_PASSWORD_REQUEST = "POST_TEACHER_PASSWORD_REQUEST";
export const POST_TEACHER_PASSWORD_SUCCESS = "POST_TEACHER_PASSWORD_SUCCESS";
export const POST_TEACHER_PASSWORD_FAIL = "POST_TEACHER_PASSWORD_FAIL";
export const POST_TEACHER_PASSWORD_RESET = "POST_TEACHER_PASSWORD_RESET";
