export const GET_ALL_ASSIGNMENT_STUDENT_REQUEST = "GET_ALL_ASSIGNMENT_STUDENT_REQUEST";
export const GET_ALL_ASSIGNMENT_STUDENT_SUCCESS = "GET_ALL_ASSIGNMENT_STUDENT_SUCCESS";
export const GET_ALL_ASSIGNMENT_STUDENT_FAIL = "GET_ALL_ASSIGNMENT_STUDENT_FAIL";
export const GET_ALL_ASSIGNMENT_STUDENT_RESET = "GET_ALL_ASSIGNMENT_STUDENT_RESET";

export const GET_ASSIGNMENT_LIST_STUDENT_REQUEST = "GET_ASSIGNMENT_LIST_STUDENT_REQUEST";
export const GET_ASSIGNMENT_LIST_STUDENT_SUCCESS = "GET_ASSIGNMENT_LIST_STUDENT_SUCCESS";
export const GET_ASSIGNMENT_LIST_STUDENT_FAIL = "GET_ASSIGNMENT_LIST_STUDENT_FAIL";
export const GET_ASSIGNMENT_LIST_STUDENT_RESET = "GET_ASSIGNMENT_LIST_STUDENT_RESET";

export const GET_SINGLE_ASSIGNMENT_STUDENT_REQUEST = "GET_SINGLE_ASSIGNMENT_STUDENT_REQUEST";
export const GET_SINGLE_ASSIGNMENT_STUDENT_SUCCESS = "GET_SINGLE_ASSIGNMENT_STUDENT_SUCCESS";
export const GET_SINGLE_ASSIGNMENT_STUDENT_FAIL = "GET_SINGLE_ASSIGNMENT_STUDENT_FAIL";
export const GET_SINGLE_ASSIGNMENT_STUDENT_RESET = "GET_SINGLE_ASSIGNMENT_STUDENT_RESET";

export const PUT_SINGLE_ASSIGNMENT_STUDENT_REQUEST = "PUT_SINGLE_ASSIGNMENT_STUDENT_REQUEST";
export const PUT_SINGLE_ASSIGNMENT_STUDENT_SUCCESS = "PUT_SINGLE_ASSIGNMENT_STUDENT_SUCCESS";
export const PUT_SINGLE_ASSIGNMENT_STUDENT_FAIL = "PUT_SINGLE_ASSIGNMENT_STUDENT_FAIL";
export const PUT_SINGLE_ASSIGNMENT_STUDENT_RESET = "PUT_SINGLE_ASSIGNMENT_STUDENT_RESET";

export const DOWNLOAD_ASSIGNMENT_STUDENT_REQUEST = "DOWNLOAD_ASSIGNMENT_STUDENT_REQUEST";
export const DOWNLOAD_ASSIGNMENT_STUDENT_SUCCESS = "DOWNLOAD_ASSIGNMENT_STUDENT_SUCCESS";
export const DOWNLOAD_ASSIGNMENT_STUDENT_FAIL = "DOWNLOAD_ASSIGNMENT_STUDENT_FAIL";
export const DOWNLOAD_ASSIGNMENT_STUDENT_RESET = "DOWNLOAD_ASSIGNMENT_STUDENT_RESET";

export const DOWNLOAD_SUBMITTED_ASSIGNMENT_STUDENT_REQUEST = "DOWNLOAD_SUBMITTED_ASSIGNMENT_STUDENT_REQUEST";
export const DOWNLOAD_SUBMITTED_ASSIGNMENT_STUDENT_SUCCESS = "DOWNLOAD_SUBMITTED_ASSIGNMENT_STUDENT_SUCCESS";
export const DOWNLOAD_SUBMITTED_ASSIGNMENT_STUDENT_FAIL = "DOWNLOAD_SUBMITTED_ASSIGNMENT_STUDENT_FAIL";
export const DOWNLOAD_SUBMITTED_ASSIGNMENT_STUDENT_RESET = "DOWNLOAD_SUBMITTED_ASSIGNMENT_STUDENT_RESET";

