export const GET_ALL_ASSIGNMENT_REQUEST = "GET_ALL_ASSIGNMENT_REQUEST";
export const GET_ALL_ASSIGNMENT_SUCCESS = "GET_ALL_ASSIGNMENT_SUCCESS";
export const GET_ALL_ASSIGNMENT_FAIL = "GET_ALL_ASSIGNMENT_FAIL";
export const GET_ALL_ASSIGNMENT_RESET = "GET_ALL_ASSIGNMENT_RESET";

export const GET_ASSIGNMENT_LIST_REQUEST = "GET_ASSIGNMENT_LIST_REQUEST";
export const GET_ASSIGNMENT_LIST_SUCCESS = "GET_ASSIGNMENT_LIST_SUCCESS";
export const GET_ASSIGNMENT_LIST_FAIL = "GET_ASSIGNMENT_LIST_FAIL";
export const GET_ASSIGNMENT_LIST_RESET = "GET_ASSIGNMENT_LIST_RESET";

export const GET_SINGLE_ASSIGNMENT_REQUEST = "GET_SINGLE_ASSIGNMENT_REQUEST";
export const GET_SINGLE_ASSIGNMENT_SUCCESS = "GET_SINGLE_ASSIGNMENT_SUCCESS";
export const GET_SINGLE_ASSIGNMENT_FAIL = "GET_SINGLE_ASSIGNMENT_FAIL";
export const GET_SINGLE_ASSIGNMENT_RESET = "GET_SINGLE_ASSIGNMENT_RESET";

export const PUT_SINGLE_ASSIGNMENT_REQUEST = "PUT_SINGLE_ASSIGNMENT_REQUEST";
export const PUT_SINGLE_ASSIGNMENT_SUCCESS = "PUT_SINGLE_ASSIGNMENT_SUCCESS";
export const PUT_SINGLE_ASSIGNMENT_FAIL = "PUT_SINGLE_ASSIGNMENT_FAIL";
export const PUT_SINGLE_ASSIGNMENT_RESET = "PUT_SINGLE_ASSIGNMENT_RESET";

export const DOWNLOAD_ASSIGNMENT_REQUEST = "DOWNLOAD_ASSIGNMENT_REQUEST";
export const DOWNLOAD_ASSIGNMENT_SUCCESS = "DOWNLOAD_ASSIGNMENT_SUCCESS";
export const DOWNLOAD_ASSIGNMENT_FAIL = "DOWNLOAD_ASSIGNMENT_FAIL";
export const DOWNLOAD_ASSIGNMENT_RESET = "DOWNLOAD_ASSIGNMENT_RESET";

export const DOWNLOAD_SUBMITTED_ASSIGNMENT_REQUEST = "DOWNLOAD_SUBMITTED_ASSIGNMENT_REQUEST";
export const DOWNLOAD_SUBMITTED_ASSIGNMENT_SUCCESS = "DOWNLOAD_SUBMITTED_ASSIGNMENT_SUCCESS";
export const DOWNLOAD_SUBMITTED_ASSIGNMENT_FAIL = "DOWNLOAD_SUBMITTED_ASSIGNMENT_FAIL";
export const DOWNLOAD_SUBMITTED_ASSIGNMENT_RESET = "DOWNLOAD_SUBMITTED_ASSIGNMENT_RESET";

