export const GET_ALL_ANNOUNCEMENT_STUDENT_REQUEST =
  "GET_ALL_ANNOUNCEMENT_STUDENT_REQUEST";
export const GET_ALL_ANNOUNCEMENT_STUDENT_SUCCESS =
  "GET_ALL_ANNOUNCEMENT_STUDENT_SUCCESS";
export const GET_ALL_ANNOUNCEMENT_STUDENT_FAIL =
  "GET_ALL_ANNOUNCEMENT_STUDENT_FAIL";
export const GET_ALL_ANNOUNCEMENT_STUDENT_RESET =
  "GET_ALL_ANNOUNCEMENT_STUDENT_RESET";

export const GET_LIST_ANNOUNCEMENT_STUDENT_REQUEST =
  "GET_LIST_ANNOUNCEMENT_STUDENT_REQUEST";
export const GET_LIST_ANNOUNCEMENT_STUDENT_SUCCESS =
  "GET_LIST_ANNOUNCEMENT_STUDENT_SUCCESS";
export const GET_LIST_ANNOUNCEMENT_STUDENT_FAIL =
  "GET_LIST_ANNOUNCEMENT_STUDENT_FAIL";
export const GET_LIST_ANNOUNCEMENT_STUDENT_RESET =
  "GET_LIST_ANNOUNCEMENT_STUDENT_RESET";

export const ANNOUNCEMENT_STUDENT_FCM_REQUEST =
  "ANNOUNCEMENT_STUDENT_FCM_REQUEST";
export const ANNOUNCEMENT_STUDENT_FCM_SUCCESS =
  "ANNOUNCEMENT_STUDENT_FCM_SUCCESS";
export const ANNOUNCEMENT_STUDENT_FCM_FAIL = "ANNOUNCEMENT_STUDENT_FCM_FAIL";
export const ANNOUNCEMENT_STUDENT_FCM_RESET = "ANNOUNCEMENT_STUDENT_FCM_RESET";
